select = ["ALL"]
ignore = ["ANN101", "ANN102", "D203", "D211", "D212", "D213", "D401", "INP001", "UP009", "S101", "BLE001", "SLF001", "PERF203", "RUF015", "TD", "FIX", "TID252", "TCH002", "PLC0414"]

exclude = ["docs"]
